spring.application.name=job-portal


spring.profiles.active=dev
spring.datasource.url=jdbc:mysql://localhost:3306/job_portal?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=shlok6123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
